### ISSUE TITLE
restarts roughly every 6 h

### ISSUE THREAD

**Issue by ivukotic** [ssl-hep/X509_Secrets#10]
deployment restarts. this is what it leaves in the log:
Your proxy is valid until Tue Jan 12 18:27:31 UTC 2021
Created Secret servicex-x509-proxy
Traceback (most recent call last):
  File "x509_updater.py", line 97, in <module>
    client.CoreV1Api().create_namespaced_secret(namespace=pod_namespace, body=secret)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 6819, in create_namespaced_secret
    (data) = self.create_namespaced_secret_with_http_info(namespace, body, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 6910, in create_namespaced_secret_with_http_info
    collection_formats=collection_formats)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 377, in request
    body=body)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 12 Jan 2021 12:27:32 GMT', 'Content-Length': '222'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \"servicex-x509-proxy\" already exists","reason":"AlreadyExists","details":{"name":"servicex-x509-proxy","kind":"secrets"},"code":409}

**Comment by robrwg** [comment]
which service component is involved here?  (who's doing the logging?)

**Comment by ivukotic** [comment]
> which service component is involved here? (who's doing the logging?)

this is a servicex-x509-proxy pod. it should renew proxy. Log is it's regular k8s log. Without looking at the code, my guess is that it tries to register new secret without deleting the old one. Not sure why would it do that at all.

**Comment by robrwg** [comment]
Can anyone take a look/fix?

**Comment by ivukotic** [comment]
I will look at it.
